server:
  port:8080

debug: false

spring:
  datasource:
    url: jdbc:h2:mem:jpa
    username: sa
    password: password
    driver-class-name: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
    show-sql: true
  data:
    rest:
      base-path: /api
  h2:
    console:
      enabled: true
      path: /h2

