server:
  port: 8080
logging:
  level:
    org.springframework.cloud.gateway.route.RouteDefinitionLocator: INFO
    org.springframework.cloud.gateway: TRACE
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: get-all-items             # http://localhost:8080/api/v1/items/
          uri: lb://ITEM-SERVICE/   # Destination
          predicates:
            - Method=GET
            - Path=/api/v1/items/
        - id: get-item-by-code          # http://localhost:8080/api/v1/items/I001
          uri: lb://ITEM-SERVICE/
          predicates:
            - Method=GET
            - Path=/api/v1/items/{code}
        - id: search-items-by-list-of-item-codes      # http://localhost:8080/api/v1/items/search-code
          uri: lb://ITEM-SERVICE/
          predicates:
            - Method=POST
            - Path=/api/v1/items/search-codes
        - id: create-new-order
          uri: lb://ORDER-SERVICE
          predicates:
            - Method=POST
            - Path=/api/v1/orders

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
