server:
  port: 9090
spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      routes:
        - id: list-all-items
          uri: lb://CUSTOMER-SERVICE
          predicates:
            - Path=/api/v1/customer/**
            - Method=GET,POST
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway: DEBUG
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
